name: Build and push docker image
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    uses: myx-ad/workflows/.github/workflows/build-and-push.yml@master
    with:
      project: "platform/supersplat"
      oci-repo: "harbor.myxrobotics.com"
    secrets:
      password: ${{ secrets.HARBOR_ROBOT_PASS }}
      npm_token: ${{ secrets.NPM_TOKEN }}
