name: Build and push docker image
permissions:
  contents: read
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

env:
  OCI_REPO: harbor.myxrobotics.com
  PROJECT: platform/supersplat

jobs:
  build:
    permissions:
      contents: read
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.OCI_REPO }}
          username: ${{ vars.HARBOR_ROBOT }}
          password: ${{ secrets.HARBOR_ROBOT_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.OCI_REPO }}/${{ env.PROJECT }}
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore .npmrc
        run: |
          echo "@myx-ad:registry=https://npm.pkg.github.com/" > ${{ github.workspace }}/.npmrc
          if [ -n "$NPM_TOKEN" ]; then
            echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> ${{ github.workspace }}/.npmrc
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secret-files: "npmrc=${{ github.workspace }}/.npmrc"
