name: Bump version
concurrency: bump-version

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: "Version type"
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Configure Git bot user
        run: |
          git config user.name 'myx-service'
          git config user.email 'service@myxrobotics.com'

      - name: Bump version
        run: npm version ${{ github.event.inputs.version-type }}

      - name: Push version changes
        run: git push --follow-tags
